version: "3.8"

services:
  app:
    build: .
    container_name: task-manager-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasksdb
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
