spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/tasksdb
    username: task
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.example.com
    port: 587
    username: lucile.toy24@ethereal.email
    password: YnjhT8vJWm5BE2N5vq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  #main:
    #allow-bean-definition-overriding: true

external-api:
  url: https://api.restful-api.dev/objects



